#!/usr/bin/env python3
"""Generate the comparative country typology table and radar chart.

Inputs:  ../data/country_data.yaml
Outputs: ../tables/tbl_country_comparison.tex
         ../figures/fig_country_radar.pdf
         ../figures/fig_subject_weight_comparison.pdf
"""

import math
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import yaml

matplotlib.use("Agg")

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "country_data.yaml"
OUT_TABLE = ROOT / "tables" / "tbl_country_comparison.tex"
OUT_RADAR = ROOT / "figures" / "fig_country_radar.pdf"
OUT_WEIGHT = ROOT / "figures" / "fig_subject_weight_comparison.pdf"

MODEL_LABEL = {
    "dual_primary_secondary": "Mandatory dual (asymmetric)",
    "dual_primary_secondary_contested": "Dual asymmetric (contested)",
    "dual_optional": "Dual optional",
    "major_minor": "Major/Minor",
    "major_minor_or_pgce": "Major/Minor + PGCE",
}

MODEL_COLOUR = {
    "dual_primary_secondary": "#2E86C1",
    "dual_primary_secondary_contested": "#E67E22",
    "dual_optional": "#5DADE2",
    "major_minor": "#8E44AD",
    "major_minor_or_pgce": "#16A085",
}


def latex_escape(s) -> str:
    if s is None:
        return "--"
    s = str(s)
    repl = {
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
        "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for k, v in repl.items():
        s = s.replace(k, v)
    return s


def write_table(countries: list[dict]):
    lines = [
        "% Auto-generated by scripts/04_country_table_radar.py — do not edit.",
        r"\begin{table}[!t]",
        r"  \centering",
        r"  \caption{Comparative typology of dual-subject teacher preparation models.",
        r"    Subject-content weights are expressed as a share of subject-content ECTS",
        r"    (excluding pedagogy, practicum, and statutory deductions); ``--'' indicates",
        r"    that the share is contested or not fixed in regulation.}",
        r"  \label{tab:country-comparison}",
        r"  \footnotesize",
        r"  \begin{tabular}{llrrll}",
        r"    \toprule",
        r"    Code & Country & Pri. \% & Sec. \% & Model type & Degree structure \\",
        r"    \midrule",
    ]
    for c in countries:
        wp = c.get("weight_primary_pct")
        ws = c.get("weight_secondary_pct")
        wp_s = f"{wp}" if wp is not None else "--"
        ws_s = f"{ws}" if ws is not None else "--"
        lines.append(
            "    {id} & {name} & {wp} & {ws} & {model} & {deg} \\\\".format(
                id=latex_escape(c["id"]),
                name=latex_escape(c["name"]),
                wp=wp_s, ws=ws_s,
                model=latex_escape(MODEL_LABEL.get(c["model_type"], c["model_type"])),
                deg=latex_escape(c["degree_structure"].replace("_", " ")),
            )
        )
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
    ]
    OUT_TABLE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[04] Wrote {OUT_TABLE}")


def plot_weight_bar(countries: list[dict]):
    has_data = [c for c in countries
                if c["weight_primary_pct"] is not None and c["weight_secondary_pct"] is not None]
    fig, ax = plt.subplots(figsize=(8.5, 4.6))
    x = np.arange(len(has_data))
    w = 0.36
    primary = [c["weight_primary_pct"] for c in has_data]
    secondary = [c["weight_secondary_pct"] for c in has_data]
    ax.bar(x - w / 2, primary, width=w, color="#2E86C1", label="Primary subject (Hauptfach / major)")
    ax.bar(x + w / 2, secondary, width=w, color="#E74C3C", label="Additional subject (Nebenfach / minor)")
    ax.axhline(50, color="#888888", linestyle="--", linewidth=0.8)
    ax.text(len(x) - 0.5, 51, "50/50 reference", color="#888888", fontsize=9, ha="right")
    ax.set_xticks(x)
    ax.set_xticklabels([c["id"] for c in has_data])
    ax.set_ylabel("Subject-content ECTS share (%)")
    ax.set_title("Primary vs. additional subject weight in dual-subject teacher programmes")
    ax.set_ylim(0, 90)
    ax.legend(frameon=False, fontsize=9)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    for xi, val in zip(x - w / 2, primary):
        ax.text(xi, val + 1.5, f"{val}", ha="center", fontsize=8.5)
    for xi, val in zip(x + w / 2, secondary):
        ax.text(xi, val + 1.5, f"{val}", ha="center", fontsize=8.5)
    fig.tight_layout()
    fig.savefig(OUT_WEIGHT)
    plt.close(fig)
    print(f"[04] Wrote {OUT_WEIGHT}")


def plot_radar(countries: list[dict]):
    """Radar of the four asymmetry dimensions per country."""
    # Dimensions: primary_weight, secondary_weight, duration, asymmetry_gap
    rows = []
    for c in countries:
        if c["weight_primary_pct"] is None:
            continue
        primary = c["weight_primary_pct"]
        secondary = c["weight_secondary_pct"]
        gap = abs(primary - secondary)
        duration = c["duration_years"] * 10  # bring to 0-100 scale (5y -> 50)
        rows.append({
            "id": c["id"],
            "values": [primary, secondary, duration, gap],
            "model": c["model_type"],
        })

    axes_labels = ["Primary %", "Additional %", "Duration ×10", "Asymmetry gap"]
    n = len(axes_labels)
    angles = [i / n * 2 * math.pi for i in range(n)] + [0]

    fig, ax = plt.subplots(figsize=(8.0, 8.0), subplot_kw=dict(polar=True))
    palette = plt.get_cmap("tab10").colors
    for i, row in enumerate(rows):
        vals = row["values"] + row["values"][:1]
        colour = MODEL_COLOUR.get(row["model"], palette[i % len(palette)])
        ax.plot(angles, vals, color=colour, linewidth=1.6, label=row["id"])
        ax.fill(angles, vals, color=colour, alpha=0.12)
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(axes_labels, fontsize=10)
    ax.set_yticks([20, 40, 60, 80])
    ax.set_yticklabels(["20", "40", "60", "80"], fontsize=8)
    ax.set_ylim(0, 90)
    ax.set_title("Cross-country structural profile of dual-subject programmes",
                 fontsize=11, pad=18)
    ax.legend(loc="lower right", bbox_to_anchor=(1.20, -0.02), fontsize=9, frameon=False)
    fig.tight_layout()
    fig.savefig(OUT_RADAR)
    plt.close(fig)
    print(f"[04] Wrote {OUT_RADAR}")


def main():
    with open(DATA, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    countries = data["countries"]
    write_table(countries)
    plot_weight_bar(countries)
    plot_radar(countries)


if __name__ == "__main__":
    main()
