#!/usr/bin/env python3
"""Reproduce the 180-ECTS arithmetic Sp4 performed in the 2026-04-21 transcript.

The chain (from File 2 / lines 70-99):
    180 total
  -  45 electives (25 % statutory)
  =  135 mandatory
  -  30 practicum
  -   3 BЖД (civil defence)
  -   3 anti-corruption / integrity
  -   3 foreign language (assumed)
  -   2 national security doctrine (assumed)
  =  ~94 remaining for content + pedagogy
  -  60 pedagogy / psychology block
  =  ~34 ECTS net for *both* subjects' content

Outputs:
  ../tables/tbl_ects_breakdown.tex
  ../figures/fig_ects_breakdown.pdf
"""

from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt

matplotlib.use("Agg")

ROOT = Path(__file__).resolve().parents[1]
OUT_TABLE = ROOT / "tables" / "tbl_ects_breakdown.tex"
OUT_FIG = ROOT / "figures" / "fig_ects_breakdown.pdf"

STAGES = [
    # (stage label,        deduction, running_total, source citation key)
    ("Bachelor total",            0,  180, ""),
    ("− 25 % student-elective",  -45, 135, "ZakonProVO:2014"),
    ("− Pedagogical practicum",  -30, 105, "MON:Practicum"),
    ("− Civil defence (БЖД)",     -3, 102, "ZakonBZD"),
    ("− Anti-corruption / integrity", -3, 99, "MONIntegrity"),
    ("− Foreign language",        -3,  96, "MONForeignLang"),
    ("− National security doctr.",-2,  94, "MONNationalSecurity"),
    ("− Pedagogy / psychology",  -60,  34, "MONPedagogyBlock"),
    ("Net for two subjects",       0,  34, ""),
]


def write_table():
    lines = [
        "% Auto-generated by scripts/05_ects_visualization.py — do not edit.",
        r"\begin{table}[!t]",
        r"  \centering",
        r"  \caption{Reconstruction of the 180-ECTS Bachelor budget after statutory deductions.",
        r"    The chain reproduces the live calculation by an accreditation expert in the",
        r"    2026-04-21 round-table (Speaker~4). Each statutory deduction is anchored",
        r"    in current Ukrainian higher-education legislation; the 60-ECTS pedagogy/psychology",
        r"    block reflects the standard claimed by accreditation expert groups.}",
        r"  \label{tab:ects-breakdown}",
        r"  \footnotesize",
        r"  \begin{tabular}{lrrl}",
        r"    \toprule",
        r"    Stage & Deduction & Remaining ECTS & Source / authority \\",
        r"    \midrule",
    ]
    for label, ded, rem, src in STAGES:
        ded_s = "" if ded == 0 else f"{ded:+d}"
        src_s = f"\\cite{{{src}}}" if src else ""
        lines.append(f"    {label} & {ded_s} & {rem} & {src_s} \\\\")
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
    ]
    OUT_TABLE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[05] Wrote {OUT_TABLE}")


def plot_waterfall():
    labels = [s[0] for s in STAGES]
    remainings = [s[2] for s in STAGES]
    deductions = [s[1] for s in STAGES]

    fig, ax = plt.subplots(figsize=(9.5, 5.0))
    xs = list(range(len(labels)))

    # Bars: remaining at each stage
    bar_colours = []
    for label, ded, rem, _ in STAGES:
        if ded < 0:
            bar_colours.append("#C0392B")  # deduction step
        elif rem == 180:
            bar_colours.append("#2E86C1")  # start
        else:
            bar_colours.append("#27AE60")  # final
    bars = ax.bar(xs, remainings, color=bar_colours, edgecolor="white", linewidth=0.5)

    for x, (label, ded, rem, _) in zip(xs, STAGES):
        ax.text(x, rem + 3, f"{rem}", ha="center", fontsize=9.5, fontweight="bold")
        if ded < 0:
            ax.text(x, rem / 2, f"{ded}", ha="center", color="white",
                    fontsize=9, fontweight="bold")

    ax.set_xticks(xs)
    ax.set_xticklabels(labels, rotation=28, ha="right", fontsize=9.5)
    ax.set_ylabel("ECTS remaining")
    ax.set_title("180-ECTS bachelor budget: how much is left for two subjects?")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_ylim(0, 200)
    ax.axhline(34, color="#888888", linestyle=":", linewidth=0.9)
    ax.text(len(xs) - 0.4, 38, "≈ 34 ECTS net", color="#555555", fontsize=9)
    fig.tight_layout()
    fig.savefig(OUT_FIG)
    plt.close(fig)
    print(f"[05] Wrote {OUT_FIG}")


def main():
    write_table()
    plot_waterfall()


if __name__ == "__main__":
    main()
