#!/usr/bin/env python3
"""Generate the LaTeX summary table for the accreditation-remarks analysis.

Reads  data/naqa/remarks/analysis_dataset.csv (from 16_analyze_remarks.py)
Writes tables/tbl_accreditation_remarks.tex  (cross-tab: parity/balance pressure x outcome)

The table is inlined into paper/manuscript.tex (the manuscript does not \\input tables/).
"""

import csv
from math import comb
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parents[1]
REM = ROOT / "data" / "naqa" / "remarks"
OUT = ROOT / "tables" / "tbl_accreditation_remarks.tex"


def fisher_two_tailed(a, b, c, d):
    row1, row2, col1, n = a + b, c + d, a + c, a + b + c + d
    def p(x):
        cc = col1 - x
        if x < 0 or cc < 0 or row1 - x < 0 or row2 - cc < 0:
            return 0.0
        return comb(row1, x) * comb(row2, cc) / comb(n, col1)
    p_obs = p(a)
    return sum(p(x) for x in range(0, min(row1, col1) + 1) if p(x) <= p_obs + 1e-12)


def main():
    rows = list(csv.DictReader(open(REM / "analysis_dataset.csv", encoding="utf-8")))
    def B(v): return str(v).strip().lower() == "true"
    press = [r for r in rows if B(r["parity_pressure"])]
    nopress = [r for r in rows if not B(r["parity_pressure"])]

    def cell(rs, outc):
        return sum(r["outcome"] == outc for r in rs)
    grid = {}
    for lab, rs in (("press", press), ("nopress", nopress)):
        grid[lab] = {o: cell(rs, o) for o in ("accredited", "conditional", "refused")}
        grid[lab]["total"] = len(rs)
        grid[lab]["nonclean"] = cell(rs, "conditional") + cell(rs, "refused")

    a = grid["press"]["nonclean"]; b = grid["press"]["total"] - a
    c = grid["nopress"]["nonclean"]; d = grid["nopress"]["total"] - c
    p = fisher_two_tailed(a, b, c, d)
    tot_nc = a + c; N = len(rows)
    n_balance = sum(B(r["sonnet_has_balance"]) for r in rows)
    eg = sum(int(r["n_EG"]) for r in rows); ger = sum(int(r["n_GER"]) for r in rows)
    total_rem = sum(int(r["n_balance_remarks"]) for r in rows)

    def pct(x, n): return f"{100*x/n:.0f}\\,\\%"

    tex = f"""% Auto-generated by scripts/18_remarks_tables.py from data/naqa/remarks/analysis_dataset.csv
\\begin{{table}}[!t]
  \\centering
  \\caption{{Accreditation treatment of subject-component balance in the {N} completed dual-subject
  speciality~014 programmes ({grid['press']['total']+grid['nopress']['total']} cases; {sum(B(r['sonnet_has_balance']) for r in rows)} of {N} carried at least one
  substantive remark on the distribution between the primary and additional subject, {total_rem} remarks in
  total, raised overwhelmingly by the expert group ({eg}) and the Sectoral Expert Council ({ger})).
  Rows distinguish cases in which the expert group or Sectoral Expert Council exerted explicit
  parity/balance pressure (treating an uneven primary/additional credit ratio as a deficiency, or
  requiring \\textit{{parytetnist'}}) from those in which they did not. Outcome is the final National-Agency
  decision. Retrieved {''}May~2026 from the NAQA portal \\citep{{NAQA:Portal2026}}.}}
  \\label{{tab:accred-remarks}}
  \\footnotesize
  \\begin{{tabular}}{{lrrrrr}}
    \\toprule
    & Accredited & Conditional & Refused & Total & Non-clean \\\\
    \\midrule
    Parity/balance pressure & {grid['press']['accredited']} & {grid['press']['conditional']} & {grid['press']['refused']} & {grid['press']['total']} & {pct(grid['press']['nonclean'], grid['press']['total'])} \\\\
    No such pressure & {grid['nopress']['accredited']} & {grid['nopress']['conditional']} & {grid['nopress']['refused']} & {grid['nopress']['total']} & {pct(grid['nopress']['nonclean'], grid['nopress']['total'])} \\\\
    \\midrule
    \\textit{{All}} & {grid['press']['accredited']+grid['nopress']['accredited']} & {grid['press']['conditional']+grid['nopress']['conditional']} & {grid['press']['refused']+grid['nopress']['refused']} & {N} & {pct(tot_nc, N)} \\\\
    \\bottomrule
  \\end{{tabular}}

  \\vspace{{2pt}}
  {{\\footnotesize Fisher's exact test, parity-pressure $\\times$ non-clean outcome: $p={p:.3f}$.}}
\\end{{table}}
"""
    OUT.write_text(tex, encoding="utf-8")
    print(tex)
    print(f"\n[stats] pressure non-clean {a}/{a+b} ({100*a/(a+b):.0f}%) vs no-pressure {c}/{c+d} ({100*c/(c+d):.0f}%); Fisher p={p:.3f}")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
